# Generated by Django 4.0.4 on 2022-05-30 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_home_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='home',
            old_name='num',
            new_name='car',
        ),
    ]
