# Generated by Django 4.0.4 on 2022-05-30 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0006_rename_num_home_car'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='car',
        ),
    ]
