# Generated by Django 4.0.4 on 2022-05-30 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_remove_home_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=60)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='brend',
        ),
        migrations.RemoveField(
            model_name='home',
            name='link',
        ),
        migrations.RemoveField(
            model_name='home',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='home',
            name='text',
        ),
    ]
